// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIQHRxbrPjkQVF__IgiIQUVbrC7ipU24s',
    appId: '1:961630830854:web:9b5183cb76435ae3e45e87',
    messagingSenderId: '961630830854',
    projectId: 'grocery-e7636',
    authDomain: 'grocery-e7636.firebaseapp.com',
    databaseURL: 'https://grocery-e7636-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-e7636.appspot.com',
    measurementId: 'G-ZXRXRTEYB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLixe5QZU8JJJKgJnBmnOYWq7iulQdeBI',
    appId: '1:961630830854:android:a934f821d6fc9c38e45e87',
    messagingSenderId: '961630830854',
    projectId: 'grocery-e7636',
    databaseURL: 'https://grocery-e7636-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-e7636.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvyLLarEy6oaBKOQIVcGL5dU6md88Mwbo',
    appId: '1:961630830854:ios:d90863cd114703aae45e87',
    messagingSenderId: '961630830854',
    projectId: 'grocery-e7636',
    databaseURL: 'https://grocery-e7636-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-e7636.appspot.com',
    iosBundleId: 'com.ashish.groceryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvyLLarEy6oaBKOQIVcGL5dU6md88Mwbo',
    appId: '1:961630830854:ios:897826f0d1051f95e45e87',
    messagingSenderId: '961630830854',
    projectId: 'grocery-e7636',
    databaseURL: 'https://grocery-e7636-default-rtdb.firebaseio.com',
    storageBucket: 'grocery-e7636.appspot.com',
    iosBundleId: 'com.ashish.groceryapp.RunnerTests',
  );
}
